include::rpa-home::partial$pending-review.adoc[]

== Check Value

This _Action Step_ allows you to compare two numerical or alphanumerical
(case-sensitive and case-insensitive) values to each other, using
different comparison methods.

=== Properties

*Compare Settings*

* *Compare Mode* Decide whether to compare two numerical or
alphanumerical values to each other. When using alphanumeric comparison,
the ASCII values of the given characters will be compared. For example,
"B" has an ASCII value of 66 and "a" has an ASCII value of 97, so "a" is
greater than "B", so "a" is greater than "B" would be true if upper and
lower case are taken into consideration when comparing (Compare
Alphanumeric (case-sensitive)) and false if upper and lower case are not
taken into consideration (Compare Alphanumeric (case-sensitive)).
* *Compare Operator* Define how the two values should be compared. You
can choose whether the values need to be equal or unequal, or if one
should be greater than or smaller than the other.

*Compare Values*

* *Value 1* Value to the left of the compare operator, e.g. a in a>b
* *Value 2* Value to the right of the compare operator, e.g. b in a>b

=== Inbound Variables

link:\l[*Compare Value 1*]

=== link:\l[*Compare Value 2*]Outbound Variables

*Compare Result* Returns whether the comparison was successful or not
(Bool)

=== Wizard

Note that both comparison values can be mapped to variables.
