include::rpa-home::partial$pending-review.adoc[]

= String to Array

The _String to Array_ Action Step allows you to split a string into
arrays and to process them further in the subsequent Action Steps, such
as with the _Read from Array_ Action Step.

== Properties

*Input String* (string, empty with the default setting, must not be empty) String that can be
entered using the keyboard or in the wizard, including with the help of the pin variables.

*Separator* Define a separator that the string is to be separated after.
In the wizard, you also have the option of entering the separator via a pin variable.

The separator may comprise more than one character, such as //, or also
be a space.

== Inbound Variables

//*link:#AS_StringToArray_P_InputString[Input String]*
*Input String* (string, empty with the default setting, must not be empty) String that can be
entered using the keyboard or in the wizard, including with the help of the pin variables.

//link:\l[*Separator*]
*Separator* Define a separator that the string is to be separated after.
In the wizard, you also have the option of entering the separator via a pin variable.

== Outbound Variables

*ResultAsArray* The converted string is output as an array.

== Example

1)

String = DE 123456789

Separator = space

Array output = DE;123456789

2)

String = 1234567/123/456

Separator = /

Array output 1234567;123;456
