include::rpa-home::partial$pending-review.adoc[]

== Generate Date and Time

Use _Generate date and time_ to create a configurable time stamp. Select
a country-specific style for the time stamp from the selection of format
templates or arrange the available time components as required, e.g.
day, month, and hour. You can specify the time stamp as a specific time
in the future or past, or use the current system time. It is also
possible to incorporate a time offset in days, hours, minutes, and
seconds. The time stamp generated by _Generate date and time_ will be
made available in several variables, which can be further processed in
other _Action Steps_.

=== Properties

*Generate Date and Time Settings*

The values specified for the following fields (Day, Hour, Minute, and
Second) will be incorporated into the calculation of the selected time
stamp (time offset). Positive and negative numbers can be used. The
default value is 0 in each case.

* *Day* Number of days
* **Generate day and time mode**Use the list box to select whether you
want the _Current date and time_ or a _Custom date and time_ to be used.
The time offsets from the Day, Hour, Minute, and Second fields will be
applied in both cases.
* *Hour* Number of hours
* *Minute* Number of minutes
* *Second* Number of seconds

Other Properties that are the same in all Action Steps are described in
the section on *Common Properties*. For reasons of
clarity they are not shown here.

=== Variables

The following variables relate to the configurable time stamp after any
time offset has been applied. The _Formatted_ variable will be output in
the specified _DateTime format_. The other variables will be output in
accordance with the date format settings specified in the operating
system.

* *Formatted* The _Generate date and time.Formatted_ variable provides
the time stamp using the date and time format selected.
* *Date* The _Generate date and time.Date_ variable provides the date.
* *Time* The _Generate date and time.Time_ variable provides the time.
* *Year* The _Generate date and time.Year_ variable provides the year.
* *Month* The _Generate date and time.Month_ variable provides the month
as a decimal number.
* *Day* The _Generate date and time.Day_ variable provides the day as a
decimal number.
* *Hour* The _Generate date and time.Hour_ variable provides the number
of hours.
* *Minute* The _Generate date and time.Minute_ variable provides the
number of minutes.
* *Second* The _Generate date and time.Second_ variable provides the
number of seconds.

=== Wizard

* *Generation mode* Use this radio button to select which time stamp is
used:
** *Current date and time* Use the current system time.
** *Custom date and time* Use the time selected in the *DateTime* field.
* *DateTime* Use to specify a time to be used as the *Custom date and
time*.
* *DateTime format* Select a predefined format or create a custom format
using the available time components. The _Generate date and
time.Formatted_ variable is used to output the specified format. The
following time components are available
** *dd*: Day (the day is written out as dddd).
** *MM*: Month (the month is written out as MMMM).
** *yy*: Year (the year ist written out as yyyy)
** *HH*: Hour
** *mm*: Minute
** *ss*: Second
* *Add to date* Use the following fields to specify the time offset that
should be applied to the time stamp. You can specify the required value
either by using the selector buttons or by entering the value directly.
Positive and negative numbers can be used. The default value is 0 in
each case.
** *Days* Number of days
** *Hours* Number of hours
** *Minutes* Number of minutes
** *Seconds* Number of seconds
