include::rpa-home::partial$pending-review.adoc[]

== Click App Element

The _Click App Element_ Action Step lets you perform a number of click
and/or invoke actions for an App Element. _Invoke_ means the Microsoft
API is addressed directly to execute the element function, which means
no mouse action is needed.

=== Properties

*Click App Element Settings*

*Initial Delay (ms)*: Defines how long to wait before initially
executing the configured action.

*(Additional) Modifier*: An additional key or key combination that is
active when the configured mouse action is executed.

The following choices are available: None, Ctrl, Alt, Ctrl + Alt, Shift,
Ctrl + Shift, Alt + Shift, Ctrl + Alt + Shift.

*Mouse Action:* Only available in _Mouse Action_ operation mode. Defines
which mouse action should be executed.

The following choices are available:

* {blank}
+

*None*: No action is executed. This is equivalent to a “hover”, because
the mouse is still moved to the selected element.

* {blank}
+

*Left Click*: Executes a single left-click.

* {blank}
+

*Middle Click*: Executes a single click of the middle mouse button
(usually the mouse wheel)

* {blank}
+

*Right Click*: Executes a single right-click.

* {blank}
+

*Double Left Click*: Executes a double left-click.

* {blank}
+

*Double Right Click*: Executes a double right-click.

* {blank}
+

*Wheel up*: Executes a “mouse wheel up” action, corresponding to
scrolling up one row.

* {blank}
+

*Wheel down*: Executes a “mouse wheel down” action, corresponding to
scrolling down one row.


*Operation mode*: You can select here between _Invoke Element_ and
_Mouse Action_.

* {blank}
+

*Invoke element* communicates directly with the Microsoft API to execute
the functions of the element; the mouse is not moved in this process.

* {blank}
+

*Mouse Action* simulates the configured mouse action and, in the
process, moves the mouse to the target element.

* {blank}
+
*Trigger count* defines how often the configured action should be
executed.

=== Inbound VariablesInbound Variables

*Trigger Count*

*Initial Delay*

*XPath to Element*

*Window Title*

=== Outbound VariablesOutbound Variables

The Click App Element Action Step does not have any outbound variables.

=== Wizard
In the *Mouse action*, Operation Mode you determine the type of the action (such as Double Left Click), while *Trigger Count* defines the number of times this action is performed.
The Action Step ensures that the clicks are grouped correctly. In other words, a configured double-click is executed directly, while a normal Left Click with two repetitions is executed with a time delay, to ensure that Windows does not register a double-click.

Also see Properties and the chapter Common Properties.
