= Defining Process Evaluations

Process evaluations are based on templates.

Evaluation templates contain criteria to assess feasibility and benefits of a process’s automation.

You create criteria and templates adapted to your processes.

== Before You Begin

* Obtain the Privileges you need
** To open and manage the *Process Evaluation* module, you require the Privileges *Process Evaluation Open* and *Process Evaluation Administration*.
** To open the *Evaluation Criteria* view, you also need the Privilege *Evaluation Criteria Open*.
** To create, change, and delete evaluation criteria, you need the Privileges *Evaluation Criteria Create*, *Evaluation Criteria Edit* and *Evaluation Criteria Delete*.
** To open the *Evaluation Templates* view, you also need the Privilege *Evaluation Templates Open*.
** To create, change, and delete evaluation criteria, you need the Privileges *Evaluation Template Create*, *Evaluation Template Edit*, and *Evaluation Template Delete*.

== Manage Process Evaluation Criteria

Process evaluation criteria are properties of the process that are used to assess feasibility and benefits of a process’s automation. They are graded according to the extent of their existence in the process. You can create, edit and delete criteria.

=== Create Process Evaluation Criteria

Create criteria adapted to your process.

. In the *Evaluation Criteria* view of the *Process Evaluation* module click *Create Qualifier* or *Create Benefit*.
// Which?
. Fill the form *Create new <criterion>*:
OR
 In the view that opens, fill the form:
* *Exclude*: Select the *Exclude* checkbox if the criterion can be excluded from a process evaluation, that is, it does not necessarily have to be evaluated.
When you create a process evaluation, you will then find the same checkbox next to the criterion.
* *Gradation*: Move the slide control to the right to increase the number of gradations of the criteria from 2 to 5 in increments. You can enter a description for each gradation level. The higher the level, the better the feasibility or benefits of the process automation are rated.
. Click *Save*.

=== Edit Process Evaluation Criteria

Edit criteria to make it more useful.

Evaluations of a Process that were created based on a template that contains the edited criterion are not changed. They continue to contain the criterion in its original form.
The changed form of the criterion is used in the templates as soon as the changes are saved.

// Insert Icon image
. In the *Evaluation Criteria* view of the *Process Evaluation* module click [icon] *Edit* in the table row of the criterion you want to edit.
. Edit the form *Edit <criterion>*.
. Click *Save*.

=== Delete Process Evaluation Criteria

Delete criteria you don’t use any more.

Evaluations of a Process that were created based on one of these templates are not changed and continue to contain the criterion even after it is deleted.

. In the *Evaluation Criteria* view of the *Process Evaluation* module click [icon] *Delete* in the table row of the criterion you want to delete.
. Confirm the removal of the criterion from the templates it is used in.

== Manage Process Evaluation Templates

Process evaluation templates combine criteria suitable for a specific type of process.

You can create, copy, edit and delete templates.

=== Create Process Evaluation Templates

Create different templates for different types of processes.

Instead of creating a new empty template you can also copy and edit an existing template.

. In the *Evaluation Templates* view of the *Process Evaluation* module click *Create*.
. Fill the form *Create new <template>*:
* *Available/Assigned <criteria>*:Click on a criterion to move it from Available to Assigned and vice versa.
* *Exclude MuleSoft default evaluation criteria*: select the checkbox to exclude the MuleSoft default criteria from the selection lists.
. Click *Save*.

=== Copy Process Evaluation Templates

Copy and edit templates instead of creating new empty ones to save time.

. In the *Evaluation Templates* view of the *Process Evaluation* module click [icon] *Copy* in the table row of the template you want to copy.
. Edit the form *Copy <template>*.
. Click *Save*.

=== Edit Process Evaluation Templates

Edit templates to make them more useful.

. In the *Evaluation Templates* view of the *Process Evaluation* module click [icon] *Edit* in the table row of the template you want to edit.
. Edit the form *Edit <template>*.
. Click Save.

=== Delete Process Evaluation Templates

Delete templates you no longer use.

Evaluations of a process that use a template that has been deleted are not changed.

. In the *Evaluation Templates* view of the *Process Evaluation* module click [icon] *Delete* in the table row of the template you want to delete.
. Confirm the removal of the template.

== See Also

* xref:manager-.adoc[Assigning Privileges to a User]

* xref:manager-processevaluation-overview.adoc[Overview Process Evaluation]
* xref:manager-processevaluation-proposing.adoc[Proposing a Process Candidate]
* xref:manager-processevaluation-approving.adoc[Approving a Process]
