= Proposing a Process Candidate

You evaluate a process candidate to propose it for automation.

== Before You Begin

. Obtain the Privileges you need:
* To use the *Process Evaluation* module, you require the Privilege *Process Evaluation Open*.
* The Privilege *Process Evaluation Open* only lets you view processes that you have created yourself, that is, for which you are the Process Owner. To display all the processes for a Customer in the *Process Evaluation* view, you must have the Privilege *Global Process Evaluation View*.
* To create, edit, and delete evaluations, you must also have the Privilege *Process Evaluation Administration*.
* To approve an automation process for a Center of Excellence, you must have the Privilege *Process Evaluation Approval to a CoE*. To approve directly for a Project Manager, you need the Privilege *Process Evaluation Approval to a Project Manager*.
. Create appropriate Categories in the view *Process Management* in the module *Process Automation*.

== Manage Process Evaluations

Process evaluations assess the feasibility and benefits of a process’s automation.

=== Create a process evaluation

Create a process evaluation to propose a process candidate for automation.

. In the *Process Evaluation* view of the *Process Evaluation* module click *Create*.
. Fill the form *Create Evaluation*.
. Click *OK*
. Fill the form *<process evaluation>*:
* *Manual process execution time*: time that an employee requires to carry out the process once. In the list of evaluated processes, the value *Manual process execution time* is multiplied by the value *Frequency per month* to calculate the value *Effort/month*.
* *Costs per process run*: Costs for one-time execution of the process. In the list of evaluated processes, the value *Costs per process Run* is multiplied by the value *Effort/month* to calculate the *Costs/month(€)* value.
* *Frequency per month*: Number of times the process is carried out within a one-month period. This field can only be filled if a value has already been entered in the *Manual process execution time* field. In the list of evaluated processes, the value *Frequency per month* is multiplied by the value *Manual process execution time* to calculate the *Effort/month* value.
* *Qualifiers/Benefits*: Drag the slider to the appropriate values. *Exclude* unnecessary criteria.
. Click *Save*

=== Edit a process evaluation

Edit a process evaluation to correct errors.

. In the *Process Evaluation* view of the *Process Evaluation* module click [icon] *Edit* in the table row of the evaluation you want to edit.
. Edit the form *Edit <evaluation>*.
. Click *Save*.

=== Delete a process evaluation

Delete process evaluations no longer needed.

. In the *Process Evaluation* view of the *Process Evaluation* module click [icon] *Delete* in the table row of the evaluation you want to delete.
. Confirm the deletion.

== See Also

* xref:manager-.adoc[Assigning Privileges to a User]

* xref:manager-.adoc[Categorizing processes]

* xref:manager-processevaluation-overview.adoc[Overview Process Evaluation]
* xref:manager-processevaluation-defining.adoc[Defining Process Evaluations]
* xref:manager-processevaluation-approving.adoc[Approving a Process]
