= Contemplating Which Processes to Automate

Consider four factors before starting robotic process automation:

* Standards
* Qualifiers
* Benefits
* Order

== Standards

There might be several ways in which your company processes the same task. So before proposing a business process for automation, follow these three steps:

* Collect
* Compare
* Compile

Ask all employees how they complete a certain task. Compare the answers to get the necessary steps. If possible, compile the necessary steps into one process manual and make it a standard in your company.

Standardizing business processes helps to prepare automation and avoids automating one task in multiple ways.

== Qualifiers

Qualifiers are properties of a process you use to determine whether a process can be automated and how easily this can be done.

The more of the following requirements your process meets, the easier it is to automate:

[cols="1,2"]
|===
|*Qualifier* |*Description*

|Data-driven
|Processes that are based on texts or numbers can be automated easier than processes that require understanding of images or spoken language.

|Rule-based
|The better a process can be described using rules, the higher the automation capacity. If a process has both judgement-based parts and rule-based parts, it can be partly automated. The bot carries out the rule-based process parts and waits for human decisions.

|Uses structured digital input
|For automation of a process, all involved documents should be present in digital, structured form if possible. Use the RPA Builder tools to digitize documents.

|Stable
|You can only automate a process if it always runs predictably. We refer to such a process as stable.

|===

== Benefits

Benefits are properties of a process that you use to determine how useful the automation of a process is for the company.

[cols="1,2"]
|===
|*Benefit* |*Description*

|
|

|
|

|
|

|
|

|
|

|===
