

= Measurement Points

Measurement Points are currently not supported by RPA Manager. This
means that it is currently not possible to evaluate the data on the
server. You can still use the Measurement Points in RPA Builder
because they are still displayed in the _Workflow Run Results_.

* xref:toolbox-measurement-points-checkpoint.adoc[Checkpoint]
+
Checkpoints are integrated into a Workflow in order to ascertain which part of the Workflow was reached before an error occurred.
* xref:toolbox-measurement-points-general-timer-start.adoc[General Timer Start]
+
General timers are used to measure whole Transactions. Use the _General Timer Start_ Action Step to start the timer.
* xref:toolbox-measurement-points-general-timer-stop.adoc[General Timer Stop]
+
General timers are used to measure whole Transactions. Use the _General Timer Stop_ Action Step to stop the timer.
* xref:toolbox-measurement-points-stopwatch.adoc[Stopwatch]
+
The Stopwatch is basically a combined Start/Stop Timer with a clear graphical representation.
