= Anypoint Platform Migration Overview

MuleSoft RPA is integrating with Anypoint Platform to unify the login experience and provide support for external identity providers (IdP).

To take advantage of all new features and improvements from the integration, the organization admin must send an email to rpa_migration_support@salesforce.com requesting to start the migration process for your organization. 

Before we can start migrating your organization, ensure you follow the <<pre-migration, pre-migration steps>>.

For additional questions, contact us at rpa_migration_support@salesforce.com.

== Summary of Changes

After your organization is migrated to Anypoint Platform:  

* Users log in to RPA Manager, RPA Builder, and RPA Recorder using their Anypoint Platform account. 
* Administrators configure RPA users, teams, and permissions using Access Management instead of the *User Management* module in RPA Manager.
* RPA Manager deprecates roles and user groups and starts using teams from Anypoint Platform instead. 
* RPA Manager supports using Connected Apps to connect with Anypoint Platform, which provides a more secure and improved authentication mechanism than API keys. 
* RPA Manager supports deleting users who have assigned processes and reassigning those processes to other users or teams. 

[[pre-migration]]
== Pre-migration Steps

To prepare your organization for the migration, ensure that all your RPA Manager users have an account in Anypoint Platform or the external identity provider (IdP) your organization uses to log in.

* Federated orgs
+
If your Anypoint organization is using an IdP, the administrator must ensure the RPA users have a matching account and the proper access.
+
See xref:access-management::external-identity.adoc[] for instructions and prerequisites to configure identity management for your Anypoint Platform organization. 

* Non-federated orgs
+
The migration is automatic. MuleSoft matches RPA accounts and Anypoint accounts based on the email address. 
+
** If the RPA user already has an Anypoint account with the same email, the account linking is automatic. After the migration, the user accesses RPA resources using the Anypoint account, retaining the same level of permissions. 
** If the RPA user has multiple Anypoint accounts with the same email address, the user is prompted to select the account to link when logging in.
** If the RPA user does not already have an Anypoint user with the same email, MuleSoft sends an invite automatically before the migration so the user can join Anypoint Platform. The user must configure 2FA for their new Anypoint Platform account. 


//== See Also 
