= Step 7: Publish the Automation

After finishing the testing phase, the process is now in the production phase. It is time to create deployment configurations to specify the execution settings for the process. By creating an invokable run configuration, you publish the process to Anypoint Exchange and enable MuleSoft Composer to trigger its execution. 

Before you can create an invokable run configuration, ensure that you configured your Anypoint Platform settings in RPA Manager. See xref:rpa-manager::organizationmanagement-settings.adoc#configure-anypoint-credentials[Configure Anypoint Platform Credentials] for instructions.

== Step 7.1: Create an Invokable Run Configuration

To create an invokable run configuration for a process:

. In RPA Manager, go to *My RPA* > *My Processes*.
. Click the *MuleSoft newsletter sign-up* project.
. In the *Production configurations* panel, click *Create invokable run configuration*.
. Specify a *Configuration name*, for example, *Invokable RPA Process*, and click *Next*.
. Click *Next*(this process has no activity parameters).
. Click *Next*(this test has no user tasks).
. Select *Run in secure session* and click *Next*.
. Select the bot to carry out the execution and click *Save & Publish*. 

== Next Steps

Now that you’ve published the invokable run configuration, it is time to create a Composer flow that triggers the execution of this RPA process.

Continue with: xref:automation-tutorial-composer.adoc[]

== See Also

xref:rpa-manager::processautomation-deploy.adoc[Deploying Automations]
