= User Roles and Permissions

Automating a process takes an interdisciplinary team. Knowledge, skills, and responsibilities are distributed over several different persons. Not everyone can do anything or should know anything for security reasons. These restrictions are implemented as user roles and permissions in RPA Manager.

== User Permission Scopes

Permissions determine what users of the RPA products can see and do:

* See and open
** a module
** a view
** an object and its data
* Perform an action in a view
* Create objects
* Edit data
* Transition objects
* Take decisions
* Use products
* Analyze data
* Monitor
** usage
** performance
* Report results

== User Permissions Types

Permissions have different scopes and purposes. They can be combined. 


[cols="1,2,2"]
|===
|*Permission Type* |*Scope* |*Example*

|*Privileges* / *RPA (Deprecated) Permissions*
a|* Predefined fine-granular permissions to view and process data.
* Can be compiled to individual roles.
* For some tasks users need individual permissions or assignments additional to privileges.
* Are deprecated after the migration of RPA Manager to Anypoint Access Management
a|You can guess the purpose of these example privileges from their name:

* ``Process Automation Open``
* ``Project Management``
* ``Process Evaluation Approval to a Project Manager``
* ``Open Evaluation Templates``
* ``Builder Usage``
* ``Create Global Variables``
* ``Edit Evaluation Templates``
* ``Change Project Manager``
* ``Upcoming Process Changes Administration``

|*RPA Permissions*
a|* Role-like permissions
* For some tasks users need individual permissions or assignments additional to permissions.
a|You can guess the purpose of these example privileges from their name:

* ``RPA Automations Designer``
* ``RPA Performance Analyzer``

|*Roles*
a|* Combination of privileges.
* Users can have more than one role.
* Are deprecated after the migration of RPA Manager to Anypoint Access Management
|The role ``Business User`` could include the privileges ``Activity Library Administration``, ``Activity Library Open``, ``Dashboard Open``, ``Process Automation Open``, and ``Process Recording``.

|*Assignments*
a|* Permissions valid for a phase in the lifecycle of a project.
* Enable a user to assume responsibility for a project. 
* Assignments are combined with privileges. 
a|* A user who is part of a user group marked as ``Center of Excellence`` also needs the privilege ``Process Create`` to start the automation of a process.
* RPA developers need the privilege ``Process Automation Open`` to see which newly designed processes they can build. They need the privilege `Builder Usage` and the permission for the build phase as a team member to work on the implementation of the process in RPA Builder. If senior RPA developers need to check the build first before running tests in RPA Manager, the project manager can assign them the advanced permission ``Release to Test``.

|*Individual Permission*
a|* Permissions for security relevant process elements.
* Granted only to selected users on element creation.
a| Credentials can only be used by users selected on creation.

|*Transferred Permission*
a|* API Keys are assigned to users whose identity and permission set is used to complete tasks via REST API.
* API Keys have an expiration date.
|API Keys are needed when an RPA Manager Invokable Configuration is included into a Composer Flow.

|===

== See Also

* xref:rpa-manager::index.adoc[RPA Manager Overview]
* xref:rpa-manager::usermanagement-manage.adoc#assign-privileges-to-a-user[Assign Privileges to a User]
* xref:automation-userrolesandpermissions-privilegesbymodule.adoc[List of Privileges by Module]
* xref:rpa-manager::usermanagement-assemble.adoc#designate-user-groups-as-centers-of-excellence[Designate User Groups As Centers of Excellence]
* xref:rpa-manager::processautomation-manage.adoc#projectdata-processteam[Assign Permissions to a Process Team Member]
* xref:rpa-manager::processautomation-prepare-deployment-credential.adoc[Manage Credentials]
* xref:rpa-manager::usermanagement-connect.adoc#create-an-api-key-for-a-user[Create an API key for a User].
* https://docs.mulesoft.com/access-management/[Anypoint Access Management^]
