include::rpa-home::partial$pending-review.adoc[]

= Step 1. Prerequisites for Creating an Automation

Before you begin your automation journey, verify that you have the required tools and access:

* A user account to access RPA Manager
+
If you don't have a RPA Manager user, ask an administrator from your organization to set up your credentials with:
+
** Enough privileges to access the automation modules
** Enough permissions to manage the different project phases
** The *Project Manager* flag enabled for your user
** Access to RPA Builder set up for your user
+
The xref:rpa-manager::usermanagement-overview.adoc[User Management Module] enables configuration of user privileges,  permissions, project managers, and RPA Builder assignments.
* Username and password to access MuleSoft Composer
+
If you don't have a Composer user, ask an administrator from your organization to set up your credentials.
* RPA Builder installed and configured in your environment
+
//TODO: Add link to download RPA Builder
link:------["Download RPA Builder^", role="button-primary"]
+
See the <link to Builder installation guide> for installation and configuration instructions.
* RPA Recorder installed and configured in your environment
+
//TODO: Add link to download RPA Recorder
link:------["Download RPA Recorder^", role="button-primary"]
+
See xref:rpa-recorder::getting-started.adoc[Getting Started] for installation and configuration instructions.
* RPA Bot installed and configured in your environment
+
//TODO: Add link to download RPA Bot
link:------["Download RPA Bot^", role="button-primary"]
+
See the <link to Builder installation guide> for installation and configuration instructions.

[TIP]
Use two browser windows: One to read instructions and one to perform the tasks.

== Next Steps

After you set up your environment with the necessary applications and credentials, you are ready to start evaluating processes for automation.

Continue with: xref:automation-tutorial-evaluate.adoc[Step 2: Evaluate a process for automation]

== See Also

* xref:rpa-manager::usermanagement-overview.adoc[User Management]
* xref:hardware-software-requirements.adoc[Hardware and Software Requirements]
// link to installation guides?
