= Tutorial: Create an Automation from Start to Finish

MuleSoft Robotic Process Automation (RPA) enables you to automate workflows that contain time-consuming manual tasks and integrate them with your MuleSoft Composer flows.

//During this tutorial, you create a simple automation project that accesses the MuleSoft website and subscribes to the newsletter, and then you configure a Composer flow to trigger the automated process.
During this tutorial, you create a simple automation project that accesses the MuleSoft website, subscribes to the newsletter, and then uses optical character recognition (OCR) to confirm that the process finishes successfully.

Follow these steps to complete the end-to-end automation journey:

* xref:automation-tutorial-prerequisites.adoc[]
* xref:automation-tutorial-evaluate.adoc[]
* xref:automation-tutorial-create.adoc[]
* xref:automation-tutorial-design.adoc[]
* xref:automation-tutorial-build.adoc[]
* xref:automation-tutorial-test.adoc[]
* xref:automation-tutorial-deploy.adoc[]
* xref:automation-tutorial-composer.adoc[]
* xref:automation-tutorial-monitor.adoc[]

After you've experienced the end-to-end journey, use the model you created to plan your next automation projects.

== See Also

* xref:index.adoc[RPA Overview]
