= Step 1. Prerequisites for Creating an Automation

Before you begin your automation journey, verify that you have the required tools and access:

* Username and password to access RPA Manager. If you don't have access yet, ask an administrator from your organization to provide you access credentials.
* Username and password to access MuleSoft Composer. If you don't have access yet, ask an administrator from your organization to provide you access credentials.
* Download RPA Builder, the application that enables you to build the automations by specifying action steps in the process.
+
//TODO: Add link to download RPA Builder
link:------["Download RPA Builder^", role="button-primary"]
* Download RPA Recorder, the tool that assists you during the creation of the BPMN in RPA Manager by capturing and recording input from your local environment.
+
//TODO: Add link to download RPA Recorder
link:------["Download RPA Recorder^", role="button-primary"]
* Download RPA Bot, the tool that provides the robots that run in your on=premise environment and execute the assigned automations.
+
//TODO: Add link to download RPA Bot
link:------["Download RPA Bot^", role="button-primary"]

[TIP]
Use two browser windows: One to read instructions and one to perform the tasks.

== What’s Next

After you set up your environment with the necessary applications and credentials, you are ready to start evaluating processes for automation.

Continue with: xref:automation-tutorial-evaluate.adoc[Step 2: Evaluate a process for automation]

== See Also

// link to user management article in RPA Manager
// link to hardware and software requirements
