include::rpa-home::partial$pending-review.adoc[]

= Glossary

The following glossary helps you understand MuleSoft terminology.



== A

''''''
=== Activity

A basic unit of work in the Mule application flow. This can in turn be a connector that connects to an external system or a transform step that is used to transform data inside the application.

=== Automation Credits

To be defined.


== B

''''''
=== Bot Minutes

The total number of minutes running process automations across all bot sessions. A single bot may run multiple parallel sessions, with each parallel session counting as a separate bot session and RPA Bot Minutes will be aggregated across these parallel sessions. Multiple bots may be configured to run the same process, with each of the multiple bots counting as separate bot sessions and RPA Bot Minutes will be aggregated across these separate bot sessions. Test runs or process runs in the test phase are also counted towards RPA Bot Minutes.

=== Bot tasks

Bot tasks contain the activities for the RPA bot to execute.

=== BPMN

Business Process Model and Notation (BPMN) is a standard specification for diagrams to depict business processes. Such diagrams can be created directly by the process owner and easily translated into a machine-executable program.

=== BPMN editor

An editor that is available both inside RPA Manager and RPA builder to modify existing BPMNs.


== C

''''''
=== Center of Excellence (CoE)

If the users of a user group cover the entire range of competencies required for a specific part of the automation, the group is called a _Center of Excellence (CoE)_. Only user groups explicitly designated as Centers of Excellence can accept process automation tasks.


== D

''''''

== E

''''''

== F

''''''

== G

''''''

== H

''''''

== I

''''''

=== Invocable API

To be defined.

=== Invocable/Invokable (process/production/run) configuration

To be defined.


== J

''''''

== K

''''''

== L

''''''

== M

''''''
=== ((business) process) model

To be defined.

=== MuleSoft Automation

MuleSoft Automation enables you to automate workflows that contain time-consuming manual tasks and integrate them with your MuleSoft Composer flows.

=== MuleSoft Composer

MuleSoft Composer (Composer) makes it easy to build process automation for data, using clicks instead of code. When you create a secure process to connect the information stored in different systems, you build a real-time, integrated view of your customers and your business.


== N

''''''

== O

''''''

=== OCR

Optical Character Recognition (OCR) enables you to convert images, or printed text into machine-encoded text.

=== Organization

The container for everything in your RPA Platform account.

== P

''''''

=== Process candidate

A real-life business process about to be proposed for automation via process evaluation.

=== Process owner

To be defined.

=== Project Manager

A project manager is responsible for the automation of a process across all automation phases.

== Q

''''''

== R

''''''
=== RPA

MuleSoft Robotic Process Automation (RPA) enables you to automate business processes and tasks by using bots, which helps save time and prevent introducing human errors.

=== RPA Bot

RPA bots are software robots that run in an on-premise environment and execute the assigned automations. You can manage bots from RPA Manager.

=== RPA Builder

RPA Builder is the on-premise application that enables you to build the automations by specifying the steps of the process.

=== RPA Manager

RPA Manager is the cloud-based control plane for the automations that is integrated into Anypoint Platform.

=== RPA Recorder

RPA Recorder is an on-premise tool that assists during the process building phase by automatically recording action steps from your local environment.


== S

''''''
=== Secure session

Secure Session is a hidden Windows session that runs invisibly and closed in a separate user account. The screen does not show what is happening or what information is being processed.


== T

''''''

== U

''''''
=== User tasks

User tasks are elements of a process model, which cannot be processed fully automatically by a Robot, instead requiring the support of a human.


== V

''''''

== W

''''''

== X

''''''

== Y

''''''

== Z

''''''
