= Glossary

The following glossary helps you understand MuleSoft RPA terminology.



== A

Action Step::
The smallest components in a Workflow. Use action steps to build logical blocks and transactions in RPA Builder. 

Activity::
A single unit of work in the automation project. An activity can be a bot task and its linked workflow, or a user task.

Activity Library:: 
A collection of assets that enables you to reuse certain activities that repeat during the automation of business processes, such as a login, to avoid creating the same workflow multiple times.

Activity Parameter:: 
Map variables that you can use both in the Workflow and in the activities of the business process and gateways.

Analysis Package:: 
A ZIP file containing workflow run logs and error screenshots. Importing the package in RPA Builder shows information in the same format as when the workflow executes locally.

== B

Bot Tasks::
Contains the activities for the RPA bot to execute.

BPMN (Business Process Model and Notation)::
A standard specification for diagrams to depict business processes. Such diagrams can be created directly by the process owner and easily translated into a machine-executable program.

BPMN Editor::
An editor that is available both inside RPA Manager and RPA Builder to modify existing BPMs.

== C

Center of Excellence (CoE)::
A group of users that cover the entire range of competencies required for a specific part of the automation. Only user groups explicitly designated as Centers of Excellence can accept process automation tasks.

Composer Task::
An action executed on a MuleSoft Composer Connector, including but not limited to read, create, update, and delete.

== I

IDP (Intelligent Document Processing)::
A technology solution that implements AI to read documents, extract data, and organize information from different document sources.

Invocable Run Configuration::
A run configuration that RPA Manager uploads to Anypoint Exchange as an invocable API to be called by other services such as Composer.

== M

MuleSoft Automation::
Automates workflows that contain time-consuming manual tasks and integrate them with your MuleSoft Composer flows.

== O

Optical Character Recognition (OCR)::
A technology that convert images of texts into machine-encoded text.

Organization::
The container for everything in your RPA Platform account.

== P

Properties::
A group of values that define the settings of a specific element. 

Process Candidate::
A real-life business process about to be proposed for automation via process evaluation.

Project Manager::
A project manager is responsible for the automation of a process across all automation phases.

== R

Regular Expression::
A sequence of characters and symbols that specify a match pattern to be searched in text.  

Run Configuration::
A set of execution parameters and run conditions for an automated process that includes a name, run schedule, activity parameters' starting values, and assigned user tasks and bots.

RPA (Robotic Process Automation)::
Automates business processes and tasks by using bots, which helps save time and prevent introducing human errors.

RPA Bot::
A software robot that runs in an on-premises environment and executes the assigned automation. You can manage bots from RPA Manager.

RPA API Call::
An API invocation made by a customer to perform an operation, including, but not limited to lookup, validate, create, update, or delete data in a system as part of an RPA process.
+
See the xref:ms-automation-credits-usage-types.adoc[] for additional details.

RPA Bot Minute::
The number of minutes running process automations across all bot sessions. A single bot may run multiple parallel sessions, with RPA Bot Minutes counting for each parallel session. Multiple bots may be configured to run the same process, with RPA Bot Minutes counting for each of these separate bot sessions. Test runs or process runs in the test phase are also counted towards RPA Bot Minutes.
+
See the xref:ms-automation-credits-usage-types.adoc[] for additional details.

RPA Builder::
An on-premises application that enables you to build automations by specifying the steps of the process.

RPA Manager::
The cloud-based control plane for the automations that is integrated into Anypoint Platform.

RPA Recorder::
An on-premises tool that assists during the process design phase by recording all user actions, creating click path documentation, and generating additional data to automatically create action steps in the build phase.

== S

Secure Session::
A hidden Windows session that runs invisibly and closed in a separate user account. The screen does not show what is happening or what information is being processed.


== T

Text Modules::
A set of encoded values that can map to a certain special character, a macro, a script variable, or an environment variable.

Toolbox::
The container for the action steps that you implement in RPA Builder to automate a process. 


== U

User Task::
An element of a process model, which cannot be processed fully automatically by a Robot, instead requiring the support of a human.


== V

Variable::
A value of a defined type that you can store and change during a process.

== W

Workflow::
A set of action steps that is linked to an activity. 

Workbench::
The area of RPA Builder where you can visualize and modify a workflow.
