= Invoke RPA Services from Composer

The RPA Connector for MuleSoft Composer enables you to invoke RPA processes and configure polling triggers from your Composer flows. You can use the RPA connector to invoke an RPA process, pass data to an RPA process and retrieve results from the RPA process.

The RPA Connector for MuleSoft Composer enables you to:

* *Invoke RPA Process*
+
This feature enables you to make sync and async calls to RPA processes.
+
** Sync calls wait for the RPA process to finish before continuing with the Composer flow execution.
** Async calls invoke an RPA process and continue the Composer flow execution while the RPA process executes in parallel.
* *RPA Poll Trigger*
+
This feature enables you to create listeners that check the status of an specific RPA process. When the RPA process finishes the execution, the polling trigger starts processing the configured activities in the Composer flow. This functionality is useful for retrieving results from RPA processes that take a long time to finish and are not suitable for synchronous consumption.

Before you can invoke an RPA process, you need to publish it to Exchange. See xref:rpa-manager::processautomation-deploy.adoc#create-an-invokable-run-configuration[Create an invokable run configuration] for instructions to create and publish an invokable RPA process.

Using the RPA Connector features in Composer requires you to connect with your MuleSoft RPA account by configuring the corresponding API key and RPA API URL.

////
Refer to the xref:composer::ms_composer_rpa_reference.adoc[RPA Connector] documentation in Composer for configuration and usage details.
////
