= Invoke RPA Services from Composer

MuleSoft RPA Connector for MuleSoft Composer enables you to invoke RPA processes and configure polling triggers from your Composer flows. You can use the RPA connector to invoke an RPA process, pass data to an RPA process and retrieve results from the RPA process.

The RPA connector for MuleSoft Composer enables you to:

* *Invoke RPA Process*
+
This feature enables you to make sync and async calls to RPA processes.
+
** Sync calls wait for the RPA process to finish before continuing with the Composer flow execution.
** Async calls invoke an RPA process and continue the Composer flow execution while the RPA process executes in parallel.
* *RPA Poll Trigger*
+
This feature enables you to create listeners that check the status of an specific RPA process. When the RPA process finishes the execution, the polling trigger starts processing the configured activities in the Composer flow. This functionality is useful for retrieving results from RPA processes that take a long time to finish and are not suitable for synchronous consumption.

Refer to the xref:composer::ms_composer_rpa_reference.adoc[MuleSoft RPA Connector for Composer] documentation for configuration and usage details.

== Before You Begin

* Before you can invoke an RPA process, you must publish it to Exchange. See xref:rpa-manager::processautomation-deploy.adoc#create-an-invocable-run-configuration[Create an invocable run configuration] for instructions to create and publish an invocable RPA process.

* Using the RPA connector features in Composer requires you to connect with your MuleSoft RPA account by configuring the corresponding API key and RPA API URL:

** See xref:rpa-manager::usermanagement-connect.adoc#create-an-api-key-for-a-user[Create an API Key for a User] for instructions to create API Keys.
** The RPA API URL is the RPA Manager URL with `/rpa/api/v1` appended to it. For example, if your RPA Manager URL is `+https://myOrg.rpa.mulesoft.com+`, then the value to set in the RPA API URL field is `+https://myOrg.rpa.mulesoft.com/rpa/api/v1+`.

== See Also

* xref:composer::ms_composer_prerequisites.adoc[MuleSoft Composer: Getting Started]
