include::partial$automation-credits-2.adoc[tag=title]

include::partial$automation-credits-2.adoc[tag=intro]

include::partial$automation-credits-2.adoc[tag=conversionRates]

MuleSoft adds all the RPA execution times in seconds for the period and then multiplies this raw usage by a constant multiplier to calculate the credit usage subtotal. See https://help.salesforce.com/s/articleView?id=000390885&type=1[Monthly Account Summary Email FAQ^] for more information about multipliers and usage reports. 

include::partial$automation-credits-2.adoc[tag=detailsAndSubscriptionPlans]

== Generative AI

The services contain features that use generative AI technology that may be provided by one or more third-parties as listed in the documentation applicable to the services. This documentation provides information and product requirements specific to these generative AI features and providers, including applicable third-party acceptable use policies which the customer must comply with when using the generative AI technology. Due to the nature of generative AI, the output that it generates may be unpredictable, and may include inaccurate or harmful responses. Before using any generative AI output, the customer is solely responsible for reviewing the output for accuracy, safety, and compliance with applicable laws and third-party acceptable use policies. The customer assumes all responsibility for output generated by the services and, as between Salesforce and the customer, such output is customer data.

include::idp::partial$einstein-model.adoc[tags=einsteinGeneric]

[NOTE]
Einstein doesn't use customer data to train any models for document analysis in IDP.

== See Also 

* xref:ms-automation-credits-usage-types.adoc[]
* xref:ms-automation-credits-usage-types#usage-report[Create a Usage Report]
* xref:ms-automation-credits-usage-types#monthly-summary-mails[Monthly Account Summary Emails]
