= Documents

The RPA Recorder creates three document types at the end of a recording session:

* BPMN
* PDF
* XES

All three types of documents can be found in the same directory specified the settings section.
Recordings will be grouped by date and tagged with the timestamp of the recording session.

== BPMN

The BPMN is a graphical representation of a business process model and is a crucial element of an automation project in the [XceleratorOne](xref) RPA platform.
It also includes the recorded documentation, which can be viewed in RPA Manager.

The BPMN can also be opened with any workflow and decision automation platform which supports [BPMN v2.0](xref) standard, specified by the [Object Management Group](xref).

== PDF

The created PDF is an additional documentation of a recording and contains the following information:

* Recording time.
* Process name (if opened from web client, otherwise a default name ‘New Process’ is assigned).
* BPMN graphic.
* Table with following information:
** Element name - Start Event, Activity (Service Task), End Event.
** Application window title.
** Action type – System, mouse, keyboard, clipboard, window state, variable, comment, screenshot.
** Screenshots – Either screenshots taken on mouse clicks or manual screenshots.
** Info – Detailed information based upon the action type.

Above mentioned table contains a gray background row whenever a new activity is created, the proceeding rows have a white background to indicate that the sub elements are part of this activity.

== XES

XES is the standard format for process mining. The recorder generates an XES file which can be opened with any process mining tools that supports the [XES 2.0](xref) format. The XES will be used for further process mining purposes.

== Logs

A log file is created in the “Logs” subdirectory (found within the user defined directory in the [settings section](xref)). If the process recorder directory does not exist, it will be automatically created together with a log file.
The log file contains valuable information about recording, but also warnings and errors that may have happened.

As with every software, unexpected behavior may arise, in these cases the user can provide feedback to MuleSoft by sending over the log file.
