

= Creating Alerting Email Templates

Create a template for an email that will be sent as an alert. Address the email to users within RPA Manager or to other persons that need to be aware of problems. Use keywords to extract the relevant information from the incident.

Combine targets to target groups to save time when creating alert rules.

== Before You Begin

* Obtain the needed privileges:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|Open the *Alerting* module
|Alerting Open

|Create, edit and delete alerting targets and rules.
|Alerting Administration

|===

== Create Alert Targets

Create a template for an email that will be sent as an alert. Address the email to users within RPA Manager or to other persons that need to be aware of problems. Use keywords to extract the relevant information from the incident.

. In the *Alert Targets* view of the *Alerting* module, click *Create*.
. Complete the form *Create a new email target*:
+
* *Keywords*:
+
Click on the *Keywords* icon to add placeholders to the subject or the body of the email. They will be filled with the actual values at sending time.
. Click *Save*.

== See Also

* xref:usermanagement-manage.adoc#create-a-user[Assign Privileges to a User]
* xref:alerting-overview.adoc[Alerting Overview]
* xref:alerting-rule.adoc[Defining Rules for Alerts]
