= Creating Alerting Email Templates

Create a template for an email to send as an alert. Address the email to users within RPA Manager or to other people that must be aware of problems. Use keywords to extract the relevant information from the incident.

Combine targets to target groups to save time when creating alert rules.

== Before You Begin

* Ask an organization administrator in Access Management to assign you the required permissions:
+
[%header, cols="1,1,1"]
|===
|Action |RPA Permission |Deprecated RPA Permission

|Open the *Alerting* module.
|RPA Operations Viewer, RPA Operations Manager, RPA Administrator
|Alerting Open

|Create, edit, and delete alerting targets and rules.
|RPA Operations Manager, RPA Administrator
|Alerting Administration

|===

== Create Alert Targets

Create a template for an email to send as an alert. Address the email to users within RPA Manager or to other people that must be aware of problems. Use keywords to extract the relevant information from the incident.

. In the *Alert Targets* view of the *Alerting* module, click *Create*.
. Complete the form *Create a new email target*:
+
* *Keywords*:
+
Click on the *Keywords* icon to add placeholders to the subject or the body of the email. The placeholders are filled with the actual values when RPA Manager sends the emails.
. Click *Save*.

== See Also

* xref:alerting-overview.adoc[Alerting Overview]
* xref:alerting-rule.adoc[Defining Rules for Alerts]
