= Current Bot Status

In the *Current Bot Status* widget, you can see at a glance which of your bots are ready for use.

== Data Representation

The numbers of Bots in each case are links displayed together with a graphical representation of the ratio of those Bots ready for use compared to those not ready.

The length of the green line labeled with *Ready* corresponds to the number that are ready for use; the length of the red line labeled with *Not Ready* corresponds to the number not ready.

== Configuration

This widget cannot be configured.


== Drill-down

Click on a number to obtain a list of all Bots or only those Bots with a specific status.

=== Data Representation of the Current Bot Status

The Bots are displayed in a list.

=== Columns of the *Current Bot Status* List

==== Status

===== OK

The Bot is ready for use.

===== Stopped

The Bot is not ready for use because it has been stopped.

===== No License

The Bot is not ready for use because it is not licensed.

==== Bot

Name of the bot.

Click on the name of the bot to get to its detailed view.

==== Processing

Shows if a process configuration has been deployed to the bot.
