= RPA Manager Overview

RPA Manager is the cloud-based control plane for the automations that is integrated into Anypoint Platform.

RPA Manager enables you to do the following:

* Manage user access and permissions.
* Evaluate the viability and financial benefits of implementing an automation.
* Design and document RPA processes.
* Test and deploy automations.
* Manage and monitor deployed automations.

To access RPA Manager, navigate to `https://<tenant>.rpa.mulesoft.com`, where `<tenant>` represents your organization's instance. If you are not sure about this value, contact your organization's administrator.

Ensure that access to this URL is possible from your organization.

RPA Builder, RPA Bot, and RPA Recorder use this URL to connect to your RPA Manager instance.

//== Get started

// A table with roles and starting modules for these roles?

== See Also

* xref:usermanagement-manage.adoc#iforgotmypassword[What to Do if You Forgot Your Password]

// Links to all RPA Manager modules
// Links to all RPA Products
