= Process Evaluation

A process evaluation comprises the benefits and feasibility of the automation of a real-life business process. It includes details on its costs, duration, and frequency.

If you want to propose a process candidate for automation, you evaluate it based on preconfigured criteria.

As a member of a center of excellence, you approve process candidates eligible for automation.

== Getting Started

==== Think
* What processes are there in your company?
* Who is responsible for the processes?
* Which criteria are necessary and suitable for evaluating the processes?
* How can these criteria be described clearly and comprehensively?
* Where does the data for evaluating the processes come from?
* Which systems and data are needed for automating the processes?

==== Prepare
* In the *User Management* module, give your users the privileges and properties they need.
* After making the necessary systems available, define the applications, credentials, and global variables needed to automate the processes in the *Process Automation* module.

==== Configure
. In the *Evaluation Criteria* view, create the additional criteria needed to evaluate your processes.
. In the *Evaluation Templates* view, compile the criteria needed to evaluate certain process types.

==== Evaluate
* In the *Process Evaluation* view, create an evaluation based on a template for each of your processes.

==== Automate
* Select the processes to be automated and delegate the implementation to a center of excellence.

==== Administer
* Manage the automation projects in the *Process Management* view of the *Process Automation* module.

== Definitions

==== Process candidate

A _process candidate_ is a real-life business process about to be proposed for automation via process evaluation.

==== Center of excellence

If the users of a user group cover the entire range of competencies that are required for a specific part of the automation, we refer to the group as a _center of excellence (CoE)_. Only user groups that are explicitly designated as a center of excellence can accept process automation tasks.

== See Also

* xref:manager-processevaluation-considering.adoc[Considering Which Processes to Automate]
* xref:manager-processevaluation-configuring.adoc[Configuring Process Evaluations]
* xref:manager-processevaluation-proposing.adoc[Proposing a Process Candidate for Automation]
* xref:manager-processevaluation-approving.adoc[Approving a Process for Automation]
