= Starting Automation of Approved Processes

The *Team Backlog* view contains a list of all evaluated processes for which you can claim or reject responsibility as member of a center of excellence.

If you claim a process, it is moved to your *My Backlog* view of the *My RPA* module.

Your *My Backlog* view also contains processes approved directly to you as a project manager.

You can start the automation of a process as a project manager from your backlog.

== Before You Begin

* Ask an organization administrator in Access Management to assign you the required permissions:
+
[cols="1,1,1"]
|===
|*Action* |*RPA Permission* | *Deprecated RPA Permission*

|Start automation of a process.
|RPA Automations Designer, RPA Automations Contributor, RPA Automations Manager, RPA Administrator
|Process Automation Open, Process Create

|===

* If there is no fitting category for the process in the *Process Management* view of the *Process Automation* module, create a new one.

== Claim a Process

Claim a process to assume the project manager role for the automation of this process. The process is moved to the *My Backlog* view of the *My RPA* module.

. Open the *Team Backlog* view of the *My RPA* module
. Click the icon *Claim*.

== Create a Process Project

Create a project for the process that contains administrative data.

On the *Settings* tab, you enter general data that is required for running the Process. This includes team members and applications for execution of the Process.

On the *Process Costs* tab, you enter data with which you can calculate the costs and the break-even point of the process automation. This data is required in the Finance Analysis view in the Process Operations module.


. Open the *My Backlog* view of the *My RPA* module.
. Click the icon *Start automation*.
. Complete the form *Create process*:
+
include::rpa-manager::partial$form-automationproject.adoc[]
. Click *Save*

== Reject a Process Project

Reject processes that were approved to the wrong center of excellence. The process is removed from the *My Backlog* or the *Team Backlog* view in the *My RPA* module and appears with status *Rejected* in the *Process Evaluation* view in *Process Evaluation* module.

. Open the *My Backlog* or the *Team Backlog* view of the *My RPA* module.
. Click the icon *Reject*.
