= Process Automation Overview

The *Process Automation* module is the heart of RPA Manager. After a citizen technologist evaluates processes and approves them for automation in the *Process Evaluation* module, you, as a project manager, create a project here for each suitable process by starting the automation from the *My RPA* module. A project defines the framework conditions for the execution of a process and is managed by a team.

Processes go through several phases in sequence.

. In the design phase, a citizen designer creates a model of the process using BPMN.
. During the build phase, in RPA Builder, a RPA developer fills the model with concrete instructions for the bot.
. In the test phase, a quality assurance team checks if the automated process delivers the required results.
. Then you transfer the process to the production phase, where it is carried out fully automatically.

The process team can revise the process continuously.

== Getting Started

. List all applications required for the automation of a process in the *Process Applications* view of the *Process Automation* module.
. Start the automation of a process in the *My Backlog* view of the *My RPA* module.
. Create a project containing the settings and data of the process to be automated in the *Process Management* view of the *Process Automation* module.
. In the design phase, record a process with RPA Recorder or model the process using BPMN.
. In the build phase, use RPA Builder to edit or create a machine-readable program from the model.
. In the test phase, run an automated process in a test environment.
. In the production phase, deploy the automated process to a bot and execute it either scheduled in RPA Manager, or create and publish an invokable configuration to Anypoint Exchange and use it with MuleSoft Composer or Salesforce Flow.

== Definitions

=== BPMN

_Business Process Model and Notation (BPMN)_ is a standard specification for diagrams to depict business processes. Such diagrams can be created directly by the process owner and easily translated into a machine-executable program.

== See Also

* xref:myrpa-start.adoc[Starting Automation of Approved Processes]
