= Deployment Map

The deployment map shows the current status of each run configuration of all processes for which you are a team member.

The interrelationships of processes, RPA Bots, and configurations are mapped as a network.

You can view and manage all your run configurations in one place:

* Switch between test and production configurations.
* Switch between hierarchical and star network views.
* Filter the bots and configurations by status.
* Switch directly to the detailed view of a process or a configuration.
* Execute, pause, and stop test and production configurations directly from here.

The deployment map does not show invokable run configurations that were deleted in RPA Manager. Invokable run configurations deleted in RPA Manager still exist in Anypoint Exchange, but cannot be run by the bot. The deployment map might still show invokable configuration assets deprecated in Anypoint Exchange. Make sure to sync configuration changes manually between RPA Manager and Anypoint Exchange.

== Before You Begin

* Ask an administrator to xref:usermanagement-manage.adoc#assign-privileges-to-a-user[assign you the required privileges]:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|View the process deployment map
|Process Deployment Map Open

|Execute, pause or stop configurations
|Process Automation Open

|===

* You can only view processes for which you are part of the process team.
* To execute, pause or stop configurations obtain the needed team member permissions for the respective phase.
* You cannot interact with invokable configurations.
* The deployment map shows only bots that have configurations deployed.

== Filter Configurations by Status

To show a relevant subset of the map, filter the configurations by status.

You can use the following filters:

* Deployed:
+
Show all process-configuration-bot combinations in which the configuration is deployed.
* Undeployed
+
Show all process-configuration-bot combinations in which the configuration is not deployed.
* Paused 
+
Show all process-configuration-bot combinations in which the configuration is deployed.
* Errors and warnings
+ 
Show all process-configuration-bot combinations in which errors or warnings occur.

You can refine the filter results using the same filters again.

To filter configurations by status:

. Open the *Deployment Map* view in the *Process Operations* module.
. Click the *Filter by state* icon.
. Click the filter you want to use.
. To refine the result further, deselect all filters, you do not want to use on the shown subset.

The deployment map view is updated.

To show the complete map again, click *Reset Filters*.

== Manage Configuration Executions

The actions *Start*, *Deploy*, *Pause*, *Continue*, and *Revoke process* each refer to a single configuration-bot combination. The action does not change identical configurations that are deployed to a different bot or different configurations that are deployed to the same bot.

. Open the *Deployment Map* view in the *Process Operations* module.
. Click on a process configuration element in the network and select the appropriate action from the context menu.

// What to do in case of problems

== See Also

* xref:processautomation-deploy.adoc[Deploying Automations]
// a link how to interact with Invokable Configurations
