= Streaming Processes

In the *Process Streaming* view, you see the number of configurations, RPA Bots, and sessions for each productive process. You can open a live view of the sessions of a process and watch the bot as it works.

== Before You Begin

* Ask an organization administrator in Access Management to assign you the required permissions:
+
[cols="1,1,1"]
|===
|*Action* |*RPA Permission* | *Deprecated RPA Permission*

|Open the *Process Streaming* view
|RPA Operations Viewer, RPA Operations Manager, RPA Administrator
|Process Streaming Open

|===

* Only productive processes for which at least one configuration has been created and for which you are a member of the process team are displayed.
* Check xref:processautomation-deploy.adoc#runconfig-execution-enabletaskbar[*Enable Taskbar (Start menu, taskbar buttons)*] in the run configuration to view the desktop of the computer that runs the process. Otherwise, a black screen is shown.
* xref:rpa-bot::configuration.adoc#session-settings[*Send images for process streaming*] must be enabled in the RPA Bot Configurator on the computer, where the process runs.

== Watch a Bot at Work

Watch the process stream to see what is happening right now.

. In the *Process Streaming* view of the *Process Monitoring* module, click the icon *Show process streams* in the row of the *Process* you want to watch.
. Toggle *Off / On* to activate and deactivate a stream.
. Click the *Full Screen* icon in the stream panel to display it in full-screen mode.
. Press `ESC` to exit full-screen mode and return to the overview page.

== See Also

* xref:processautomation-deploy.adoc[Deploying Automations]
* xref:rpa-bot::configuration.adoc#session-settings[RPA Bot Configurator - Session Settings]