

= Finance Analysis

In the view *Finance Analysis*, you record, monitor, and analyze the financial aspects of a Process.

You can enter all expenses for automation of the process. On the basis of the costs of manual execution of the process and the number of process runs already carried out automatically, and the expected future number of monthly process runs, the *Net profit* per month and the expected *Break-Even Point* of the process are calculated.

Costs, savings, net profit, and break-even point are shown in line charts from the time of creation of the process. The data is shown from the start of automation] within a configurable time period of a maximum of 60 months.

Each change to the raw data is reflected directly in the graphic. This way, you can analyze when the process automation pays for itself.

For the Finance Analysis, you require the following values:

* Actual and expected number of process runs per month.
* Costs of a process run if this is carried out by a human (*Cost per process run for manual process execution*).
* Initial Investment for acquisition of the MuleSoft RPA solution and all other investments.
* Period in months for depreciation of the initial investment and all other investments (*Depreciation period for initial invest (in month)*).
* Monthly operating costs of process automation (*Operating costs*).

If these details are incomplete or are missing entirely, incorrect values or no values at all (*n/a*) are displayed in the table.

You can see the overview of all processes in the *Processes for finance analysis* view and the overview of a single process in the detailed view.

== See Also

* xref:processoperations-financeanalysis-basics.adoc[Finanace Analysis Basics]
* xref:processoperations-financeanalysis-analyze.adoc[Analyze Costs and Savings]
