= Process Automation Overview

The *Process Automation* module is the heart of the RPA Manager. After a citizen technologist has evaluated processes and approved them for automation in the *Process Evaluation* module, you - as a project manager - create a project here for each suitable process by starting the automation from the *My RPA* module. A project defines the framework conditions for the execution of a process and is managed by a team.

Processes go through several phases in sequence. In the design phase, a citizen designer creates a model of the process using BPMN, and during the build phase in the RPA Builder, a RPA developer fills this model with concrete instructions for the bot. In the test phase, a quality assurance team checks if the automated process delivers the required results. Then you transfer the process to the production phase, where it is carried out fully automatically.
The process team can revise the process continuously.

== Before You Begin

* Ask an administrator to xref:usermanagement-manage.adoc#assign-privileges-to-a-user[assign you the needed privileges]:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|Open the *Process Automation Module*
|Process Automation Open

|Create process projects
|Process Create

|===

* There must be at least one process in the *My Backlog* view in the *My RPA* module.
* RPA Builder, RPA Bot, and all applications required for executing the processes must be installed and configured on a computer.
* If you want to record processes, RPA Recorder must be installed on a computer.
* If not all RPA applications are installed on the same computer, ensure that all computers have the same configuration.

== Getting Started

. List all applications required for the automation of a process in the *Process Applications* view of the *Process Automation* module.
. Start the automation of a process in the *My Backlog* view of the *My RPA* module.
. Create a project containing the settings and data of the process to be automated in the *Process Management* view of the *Process Automation* module.
. In the design phase, record a process with RPA Recorder or model the process using BPMN.
. In the build phase, use RPA Builder to edit or create a machine-readable program from the model.
. In the test phase, run an automated process in a test environment.
. In the production phase, deploy the automated process to a bot and execute it either scheduled in RPA Manager, or create and publish an invokable configuration to Anypoint Exchange and use it with MuleSoft Composer.

== Definitions

=== BPMN

_Business Process Model and Notation (BPMN)_ is a standard specification for diagrams to depict business processes. Such diagrams can be created directly by the process owner and easily translated into a machine-executable program.

== See also

* xref:myrpa-start.adoc[Starting Automation of Approved Processes]

//* xref:processautomation-overview.adoc[Process Automation]
* xref:processautomation-prepare.adoc[Preparing Process Automations]
* xref:processautomation-develop.adoc[Developing Process Automations]
* xref:processautomation-deploy.adoc[Deploying Process Automations]
