= Deployment Map

The deployment map shows the current status of the run configurations. The deployment map only shows run configurations of processes for which you are a team member.

The interrelationships of processes, RPA Bots, and configurations are mapped as a network.

You can view and manage all your run configurations in one place:

* Switch between test and production configurations.
* Switch between hierarchical and star network views.
* Filter the bots and configurations by status.
* Switch directly to the detailed view of a process or a configuration.
* Execute test configurations.
* Execute, pause, and stop production configurations.

You must manually keep configuration changes in RPA Manager and Anypoint Exchange in sync. Configurations might become out of sync in the following situations:

* Invocable run configurations deleted in RPA Manager might still exist in Anypoint Exchange, but the bot cannot run them and they do not appear in RPA Manager.
* Invocable configuration assets deprecated in Anypoint Exchange might still appear in RPA Manager.

== Before You Begin

* Ask an organization administrator in Access Management to assign you the required permissions:
+
[%header, cols="1,1,1"]
|===
|Action |RPA Permission |Deprecated RPA Permission

|View the process deployment map.
|RPA Operations Viewer, RPA Operations Manager, RPA Administrator
|Process Deployment Map Open

|===

* You can only view processes for which you are part of the process team.
* To execute, pause, or stop configurations, obtain the needed team member permissions for the respective phase.
* You cannot interact with invocable configurations.
* The deployment map shows only bots that have configurations deployed.

== Filter Configurations by Status

To show a subset of the map, filter the configurations by status.

You can use the following filters:

* Deployed:
+
Show all process-configuration-bot combinations in which the configuration is deployed.
* Undeployed
+
Show all process-configuration-bot combinations in which the configuration is not deployed.
* Paused 
+
Show all process-configuration-bot combinations in which the configuration is deployed.
* Errors and warnings
+ 
Show all process-configuration-bot combinations in which errors or warnings occur.

You can refine the filter results using the same filters again.

To filter configurations by status:

. Open the *Deployment Map* view in the *Process Operations* module.
. Click *Filter by state*.
. Select a filter.
. To refine the result, deselect the filters that you do not want to use on the shown subset.

The deployment map view is updated.

To show the complete map again, click *Reset Filters*.

== Manage Configuration Executions

The actions *Start*, *Deploy*, *Run Process Now*, *Pause*, *Continue*, and *Revoke process* refer to a single configuration. The action does not change identical configurations that are deployed to a different bot or different configurations that are deployed to the same bot.

. Open the *Deployment Map* view in the *Process Operations* module.
. Click on a process configuration element in the network and select the appropriate action from the context menu.

// What to do in case of problems

== See Also

* xref:processautomation-deploy.adoc[Deploying Automations]
// a link how to interact with Invocable Configurations
