include::rpa-home::partial$pending-review.adoc[]

= Deploying Automations

The third phase of process automation is the *Test* phase. In this phase, you can test the implemented process model in different configurations. You can transition back to *Build* phase to change the implementation.

A test plan contains start values for the activity parameters defined in RPA Builder, users who process the user tasks, the configuration of the test environment, and the executing bots.

When the tests are successful, transition to *Production* phase.

The final phase in the life-cycle of a process is the *Production* phase. This phase is structured similarly to the *Test* phase. The difference is that you do not have to start the individual process runs manually. Instead you schedule a process run configuration which is then executed automatically at defined times. Or you create an invokable run configuration and publish it to Anypoint Exchange.

== Before You Begin

* Obtain the needed privileges:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|Open the *Process Automation Module*
|*Process Automation Open*

|===

* At least one RPA Bot must be installed to deploy a process.
* A project must exist in the *Project Management* view of the *Process Automation* module.
* Obtain the needed permissions as a member of the process team in the project data sheet in the *Project Management* view of the *Process Automation* module.

== Test a Process Automation

== Deploy a Process Automation

== Publish a Process Automation to Anypoint Exchange

Projects that have already been used productively can no longer be deleted.





== See Also

* xref:
