= Deployment Map

The deployment map shows the current status of each run configuration of all processes for which you are a team member.

The interrelationships of processes, RPA Bots and configurations are mapped as a network.

View and manage run configurations:
* Switch between test and production configurations.
* Switch between bot and process centered views.
* Filter the bots and configurations by status.
* Switch directly to the detailed view of a process or a configuration.
* Execute, pause, and stop test and production configurations directly from here.

The deployment map does not show invokable run configurations that were deleted in RPA Manager. 
// Does it show invokable configurations that were deleted / deprecated in Anypoint Exchange?

== Before You Begin

* Ask an administrator to xref:usermanagement-manage.adoc#assign-privileges-to-a-user[assign you the required privileges]:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|View the process deployment map
|Process Deployment Map Open

|===

* You can only view processes for which you are part of the process team.
* To execute, pause or stop configurations obtain the needed team member permissions for the production phase.
* You cannot interact with invokable configurations.
* The deployment map shows only bots that have configurations deployed.

//== View Configurations States

== Manage Production Configuration Executions

The actions *Deploy*, *Pause*, *Continue*, and *Revoke process* each refer to a single configuration-bot combination. The action does not change identical configurations that are deployed to a different bot or different configurations that are deployed to the same bot.

. Open the *Deployment Map* view in the *Process Operations* module.
. Click on a process configuration element in the network and select the appropriate action from the context menu.

== See Also

* xref:processautomation-deploy.adoc[Deploying Automations]
// a link how to interact with Invokable Configurations
