include::rpa-home::partial$pending-review.adoc[]

= Deployment Map

The deployment map shows you the current status of each productive configuration of all processes for which you are a team member.

The interrelationships of processes, RPA Bots and Configurations are mapped by a network.

* Switch directly to the detailed view of a process or a configuration.
* Execute, pause, and stop configurations directly from here.

== Before You Begin

The following table contains the needed privileges:
+
[cols="1,2"]
|===
|*Action* |*Required Privileges*

|View the process deployment map Open.
|Process Deployment Map Open.

|===

You can only view processes for which you are part of the process team.
To execute, pause or stop configurations obtain the needed team member permissions for the production phase.

== Manage Configuration Executions

The actions *Deploy*, *Pause*, *Continue*, and *Revoke process* each refer to a single configuration-bot combination. The action does not change identical configurations that are deployed to a different bot or different configurations that are deployed to the same bot.

. Open the *Deployment Map* view in the *Process Operations* module.
. Click on a process configuration element in the network and select the appropriate action from the context menu.

== See Also

* xref:usermanagement-manage.adoc#create-a-user[Assign Privileges to a User]
* xref:processautomation-deploy.adoc[Deploying Automations]
