= Queuing Process Sessions

When more process configurations are deployed than sessions are available, RPA Manager must decide the order in which the processes are executed.

You set the priority of a process configuration by assigning it a number between 1 and 200. The smaller the number, the higher the priority.

RPA Manager inserts the deployed configurations in the session queue, as soon they are started.

Test configurations and invocable run configurations automatically have the highest priority.

The processes are executed in the following order:

. Invocable process configurations
. Test configurations
. Production configurations in ascending order of their assigned priority numbers

If two or more configurations have the same priority, the ones deployed first are executed first.

== View the Queue

View the currently processed, waiting, and future process runs in the *Session Queues* view.

. Open the *Session Queues* view of the *Process Monitoring* module.
. Select the time interval for the future processes and click *Apply*.

== See Also

* xref:processautomation-deploy.adoc[Deploying Automations]
* xref:processmonitoring-overview.adoc[Process Monitoring]
* xref:processmonitoring-stream.adoc[Streaming Processes]
//xref:processmonitoring-queue.adoc[Queueing Process Sessions]
