= Reassigning RPA Assets

If an RPA user is deleted in Anypoint Access Management, RPA assets that were assigned to this user are shown in the *Reassign Assets* tab in the *Admin Settings* view of the *Settings* module.

All users with the *Reassign Users* or *RPA Administrator* permission get an email when an RPA asset is orphaned because its last assigned user is deleted.

You can reassign the following RPA assets to another user:

* Credentials
* Process Evaluations 
* Process Projects
* Process Board Tasks 
* Alert Targets

== Before You Begin

* Ask an Anypoint Access Management administrator to assign you the required permissions:
+
[cols="1,2,2"]
|===
|*Action* |*RPA Permission (deprecated)* | *RPA Permission*

|View configured settings for your organization
|Organization Management Open
|RPA Administrator

|Add or modify settings for your organization
|Organization Management Administration
|RPA Administrator

|Reassign RPA Assets
|Reassign Users
|RPA Administrator

|===

* Ensure that the user whom you reassign an asset has the required permissions and knowledge to handle that asset.
* The following assets are deleted on the deletion of the user:
** Private dashboards
** User API Keys
* The following assets are not shown in the *Reassign Assets* view and can be reassigned via other views:
** User Tasks via the *Unprocessed User Tasks* view

== Reassign One RPA Asset 

Reassign an asset that is assigned to a deleted user. RPA Manager shows users that have the required permissions for reassignment.

To reassign a single RPA asset:

. Open the *Reassign Assets* tab in the *Admin Settings* view of the *Settings* module.
. Click the *Reassign* on the panel of the asset to reassign.
. Check and edit the form *Reassign Owner*:
+
* *Assign To*: Select a user.
* Select *Send email to the new owner* if you want to inform the selected user about the reassignment.
. Click *Save*.

RPA Manager removes the reassigned asset from the list.

A toast message informs you about the success of the reassignment.

== Reassign Several RPA Assets to One User

Reassign several assets that are assigned to a deleted user at once to one user. RPA Manager shows users that have the required permissions for reassignment.

To reassign a single RPA asset:

. Open the *Reassign Assets* tab in the *Admin Settings* view of the *Settings* module.
. Check the panel of every asset to reassign.
. Check and edit the form *Reassign Owner*:
+
* *Assign To*: Select a user.
* Select *Send email to the new owner* if you want to inform the selected user about the reassignment.
. Click *Save*.

RPA Manager removes the reassigned assets from the list.

A toast message informs you about the success of the reassignments.

== See Also

* https://docs.mulesoft.com/access-management/[Anypoint Access Management^]