// tag::title[]
= MuleSoft Automation Credits 1.0
// end::title[]

// tag::intro[]
A quantity of Automation Credits is included with certain MuleSoft Services, with the specific entitlement indicated on the Usage Details table on the Order Form for such Services. Automation Credits are consumed as you create and execute automations at the applicable multiplier rates based on the Usage Types in the following table. You can use Automation Credits with MuleSoft Composer, MuleSoft IDP, MuleSoft RPA, or a combination of these products.
// end::intro[]

// tag::conversionRates[]
[%header%autowidth.spread,cols=".^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks | IDP Document Pages
| 1 MuleSoft Automation Credit = 2 | 1 MuleSoft Automation Credit = 100 | 1 MuleSoft Automation Credit = 50 | 1 MuleSoft Automation Credit = 5
|===

// end::conversionRates[]

// tag::detailsAndSubscriptionPlans[]
You can use any combination of these activities, which aggregate over the term of your subscription (not per session), and are then converted to credits as shown. Then, the credits are deducted from your assigned quota for the subscription period.

For detailed definitions and more information, see the https://www.mulesoft.com/prod-subscription-plans[MuleSoft Product Subscription Plans^].
// end::detailsAndSubscriptionPlans[]