

= Submit Form

This _Web Automation_ object allows you to submit a form on a webpage.
It will work on any field contained within a form and submit the whole
form.

== Properties

*Webelement Find Options*

* *Screenshot The recorded screenshot is displayed here.*
* *Use Regex to find Window (Enable Regex) Use this function if you want
to use Regex when searching the window.*

Other Properties that are the same in all action steps in the _Web
Automation_ are described in the section on *Common Properties*.
//link:#CommonProperties_WebAutomation[Common Properties.]
For reasons of clarity they are not shown here.

== Inbound Variables

//link:#WA_CommonProperties_ElementXPath[*Element XPath*]
*Element XPath*

//link:#WA_CommonProperties_WindowTitle[*Window Title*]
*Window Title*

== Outbound Variables

The action step _Submit Form_ possesses no outbound variables.

== Wizard

Forms are often used on websites to collect various data. The most
common example would be a registration form to get an account to log in
to a website. _Submit Form_ is a very simple-to-use tool that allows you
to transfer the required data. Just define an element XPath to identify
the form that you want to submit.

You do not have to use the submit button to start transferring the data;
modifying any of the fields contained in the form is sufficient.
