

= Checkpoint

_Checkpoints_ are integrated into a _Workflow_ in order to ascertain
which part of the _Workflow_ was reached before an error occurred. When
a _Checkpoint_ is reached it is given the status True and saves the
length of time from starting to execute the _Workflow_ until the
_Checkpoint_ is reached.

== Properties

The action step _Checkpoint_ has no properties.

== Inbound Variables

*Suffix* can be used if the _Checkpoint_ is within the _Control Block_'s
_File Controlled Loop_. A suffix is then added to the name of the
_Checkpoint_ during every loop. Each suffix is a column entry in the
file that was imported in the _File Controlled Loop_.

== Outbound Variables

*Was Reached* is given the status True if the _Checkpoint_ was executed

* Syntax: True

*Elapsed Time* is the time taken from when the _Workflow_ starts until
the _Checkpoint_ is reached

* Syntax: [Time since Workflow start in seconds]

== See Also 

* xref:toolbox-measurement-points-checkpoint-collection.adoc[Checkpoint Collection]