= Execute Excel Macro 

Run a macro in an Excel file or sheet. You can specify and pass up to 30 variables to the macro.

== Properties

* *Common* 
+
See xref:common-properties.adoc[Common Properties] for a description.  

* *Excel Operation Settings*
** *Sheet name* 
+
Name of the sheet from which to read the value. 

* *Source Excel Operation Settings*
** *Directory path* 
+
Directory path to the source file. 
** *Macro* 
+
The macro to run. 
** *Password protected* 
+
Indicates whether the Excel file is password protected. 
+
If you select this option, specify the password in the wizard. 
** *Source file name* 
+
Name of the source file.

== Inbound Variables 

* *Macro* 
* *Directory path* 
* *Source file name* 
* *Password for the excel file* 
* *{Arg1} replaced by* ... *{Arg30} replaced by*
* *Is Arg1 used* ... *Is Arg30 used*
* *Sheet name*

== Outbound Variables 

* *Result* 
+
Result of the macro's execution.
* *Executed* (Boolean)
+
Returns `true` if the execution of the macro was successful.

== Wizard 

Specify the *Directory path* and *File name* of the Excel file that contains the macro to run.

After specifying the file, select the macro to run from the *Macro* dropdown menu. This list autopopulates with the macros existing in the specified Excel file. 

You can specify up to 30 variables to pass to the macro as arguments by selecting the corresponding checkbox and setting their value. 

== See Also

* xref:toolbox-excel-operations.adoc[]
* xref:toolbox-excel-operations-excel-session.adoc[] 