= Write Bot Message 

The Write Bot Message action step enables you to enrich the result message the RPA Bot generates after each failed run. In case of execution failure, this message shows in the *Run Results* section of the *Process Management* view in RPA Manager. 

Bot messages shouldn't exceed 2000 characters. Mapping an activity parameter containing more than 2000 characters causes the message to show truncated in RPA Manager bot message logs. To view the complete bot log, download the log files in RPA Manager.

== Properties 

* *Bot message* 
+
The text to write in the message. 
* *Overwrite message* 
+
Select this option to overwrite the previous messages shown in *Run Results*. 

== Inbound Variables 

* *Bot message* 
+
The text to write in the message. 

== Outbound Variables 

This action step has no outbound Variables. 

== See Also 

* xref:rpa-manager::botmanagement-troubleshoot#view-the-bot-log-messages[RPA Manager: View the Bot Log Messages]
* xref:rpa-manager::botmanagement-troubleshoot#download-the-log-files-of-a-bot[RPA Manager: Download the Log Files of a Bot]
