

= Checks

Checks are different types of validations that you can add as action steps of an automation project.

* xref:toolbox-checks-check-process.adoc[Check Process]
+
This action step enables you to check if a process is running or not and either kill it or launch another program.
* xref:toolbox-checks-image-search.adoc[Image Search]
+
This action step searches for a user-defined image, waits until it appears or disappears, and can also be used as a relative anchor point for mouse clicks.
* xref:toolbox-checks-screenshot.adoc[Screenshot]
+
This action step takes a screenshot and saves it to the trace folder. You can use it to get feedback on what is happening at any point in a Workflow.
* xref:toolbox-checks-search-pattern.adoc[Search Pattern]
+
The Search Pattern action step searches for one or more patterns within a defined Search Area on the screen.
* xref:toolbox-checks-window-wait.adoc[Window Wait]
+
The action step Window Wait pauses the Workflow until a certain window is displayed or not displayed.
