= Submit Document to MuleSoft IDP 

Send documents to MuleSoft IDP to be processed asynchronously with your published document actions. Each successful execution returns an execution ID that you must use when you run the Retrieve Results from MuleSoft IDP action step to query the results of said execution.

include::partial$mulesoft-idp.adoc[tag=creditsWarning]

== Before You Begin

Before using this action step, ensure that:

* Your currently logged-in Anypoint user account has read permissions for IDP. 
+
The wizard uses this user to query MuleSoft IDP for the available *Action* and *Action Version* options.
* You have IDP document actions published in your organization.
+
See xref:idp::publishing-document-actions.adoc[] for additional information.
* You have a connected app configured to access IDP. 
+
The connected app must have the *Execute Published Actions* scope in Anypoint Platform.
+
See xref:idp::automate-document-processing-with-rpa.adoc[] for configuration instructions.

== Properties

This action step has no properties other than *Common* and *Timing*. See xref:common-properties.adoc[] for further details. 

[[inbound-variables]]
== Inbound Variables

* *Directory Path*
+
Path to the directory where the file to submit is located
* *File Name*
+
Name of the file to submit
* *Client ID*
+
Client ID of the connected app configured to call IDP
* *Client Secret*
+
Client Secret of the connected app configured to call IDP
* *Connected App Credentials*
+
Pin credentials containing the Client ID and Client Secret of the connected app configured to call IDP
* *Execution ID*
+
Leave this value empty. This action step sets it automatically if it is pinned to an activity parameter; any existing value is overwritten and ignored.

include::partial$mulesoft-idp.adoc[tag=commonInboundVariables]

== Outbound Variables

* *Success*
* *ExecutionID*

[[wizard]]
== Wizard

Start by selecting the *Action* and the *Action Version* to call from IDP. These lists populate with the available document actions published by your organization in IDP. 

Then, specify the *Directory path* and *File name* of the file to submit to IDP for processing with the selected document action. 

Finally, specify the connected app credentials to use when connecting to IDP.  Either use the previously configured Pin credentials or specify the *Client ID* and *Client Secret* manually in the wizard. 

== See Also 

* xref:toolbox-mulesoft-idp-retrieve-results-from-mulesoft-idp.adoc[]
* xref:access-management::managing-permissions.adoc[]