

= Control

Control action steps enable you to interact with the system where the automation is running by sending certain instructions and input signals.

* xref:toolbox-control-clear-screen.adoc[Clear Screen]
+
This action step tries to clear any open window from the screen.
* xref:toolbox-control-enter-string.adoc[Enter String]
+
This action step emulates keyboard inputs and accepts text transferred from a previously executed action step.
* xref:toolbox-control-keystrokes.adoc[Keystrokes]
+
This action step emulates keyboard inputs.
* xref:toolbox-control-mouse-actions.adoc[Mouse Actions]
+
The Mouse Actions action step emulates mouse moves and clicks.
* xref:toolbox-control-run-program.adoc[Run Program]
+
This action step is used to run a program by directly calling its executable file.
* xref:toolbox-control-sleep.adoc[Sleep]
+
This action step causes the Workflow to be paused for the specified duration.
* xref:toolbox-control-window-set-state.adoc[Window Set State]
+
This action step allows you to change the state of a specific window.
