= Click App Element

The _Click App Element_ action step lets you perform a number of click
and/or invoke actions for an App Element. _Invoke_ means the Microsoft
API is addressed directly to execute the element function, which means
no mouse action is needed.

== Properties

* *Click App Element Settings*

** *Initial Delay (ms)*
+
Defines how long to wait before initially executing the configured action.

** *(Additional) Modifier*
+
An additional key or key combination that is active when the configured mouse action executes.
+
The following choices are available: `None`, `Ctrl`, `Alt`, `Ctrl + Alt`, `Shift`,
`Ctrl + Shift`, `Alt + Shift`, `Ctrl + Alt + Shift`.

** *Mouse Action:*
+
Only available in _Mouse Action_ operation mode. Defines which mouse action to execute.
+
The following choices are available:

*** *None*
+
Moves the mouse to the selected element and executes no action. This is equivalent to a _hover_.

*** *Left Click*
+
Executes a single left-click.

*** *Middle Click*
+
Executes a single click of the middle mouse button (usually the mouse wheel).

*** *Right Click*
+
Executes a single right-click.

*** *Double Left Click*
+
Executes a double left-click.

*** *Double Right Click*
+
Executes a double right-click.

*** *Wheel up*
+
Executes a _mouse wheel up_ action, corresponding to scrolling up one row.

*** *Wheel down*
+
Executes a _mouse wheel down_ action, corresponding to scrolling down one row.

* *Operation mode*
+
You can select here between _Invoke Element_ and _Mouse Action_.

** *Invoke element*
+
Communicates directly with the Microsoft API to execute the functions of the element; the mouse is not moved in this process.

** *Mouse Action*
+
Simulates the configured mouse action and moves the mouse to the target element.

* *Trigger count*
+
Defines how often the configured action executes.

== Inbound Variables

* *Trigger Count*
* *Initial Delay*
* *XPath to Element*
* *Window Title*

== Outbound Variables

The Click App Element action step does not have any outbound variables.

== Wizard

In the *Mouse action*, Operation Mode you determine the type of the action (such as Double Left Click), while *Trigger Count* defines the number of times this action is performed.
The action step ensures that the clicks are grouped correctly. In other words, a configured double-click is executed directly, while a normal Left Click with two repetitions is executed with a time delay, to ensure that Windows does not register a double-click.

//Also see <<Properties>> and Common Properties.
