= Retrieve Results from MuleSoft IDP 

Retrieve the results of a document processed with MuleSoft IDP. To run this action step, provide an Execution ID, generated during the execution of the Submit Document to MuleSoft IDP action step. The Execution ID links this action step with a document action execution to define which results to retrieve. 

include::partial$mulesoft-idp.adoc[tag=creditsWarning]

== Before You Begin

Before you begin using this action step, ensure that: 

* Your Anypoint user account has the Build Actions permission.
* You have the Execution ID generated from a Submit Document to MuleSoft IDP action step. 
* You have IDP document actions published in your organization.
+
See xref:idp::publishing-document-actions.adoc[] for additional information. 
* You have a connected app configured to access IDP.
+
See xref:idp::automate-document-processing-with-rpa.adoc[] for configuration instructions. 

== Properties

This action step has no properties other than *Common* and *Timing*. See xref:common-properties.adoc[] for further details. 

== Inbound Variables

* *Client ID*
+
Client ID of the connected app configured to call IDP
* *Client Secret*
+
Client Secret of the connected app configured to call IDP
* *Connected App Credentials*
+
Pin credentials containing the Client ID and Client Secret of the connected app configured to call IDP
* *Execution ID*
+
Execution ID of the document processing operation

== Outbound Variables

* *Status*
* *JSON Result*

[[wizard]]
== Wizard

Specify a combination of *Execution ID*, *Action*, and *Action Version* to query the results of that execution. These lists populate with the available document actions that your organization has published in IDP. Ensure you specify the same *Action* and *Action Version* used in the Submit Document to MuleSoft IDP configuration that generated the *Execution ID* you are checking.

Then, select the connected app credentials to use when connecting to IDP. You can use Pin credentials that you configured or specify the *Client ID* and *Client Secret* manually in the wizard. 

== See Also 

* xref:toolbox-mulesoft-idp-submit-document-to-mulesoft-idp.adoc[]
* xref:access-management::managing-permissions.adoc[]