
= Runtime Variables

The Runtime Variables action step provides a set of variables that the workflow populates at runtime. Use these variables to get information from the runtime context.

The following variables are available:

* *Project Name* 
+
Name of the _Workflow_ project
* *Project GUID* 
+
GUID of the _Workflow_ project
* *Run GUID* 
+
GUID related to the execution of the _Workflow_ (regenerated for each run)
* *Time* 
+
Actual time as local time or UTC in configurable format
* *Date* 
+
Actual date as local time or UTC in configurable format
* *HostName* 
+
Name of _Host_ system
* *UserName* 
+
Name of the user
* *RandomVariable* 
+
Positive random number with a configurable range of values. The workflow generates a different number on each run.
* *Business Process ID* 
+
ID of the business process
* *Session Id* 
+
Terminal session ID of the environment where the bot is running
* *Session Name* 
+
Terminal session name of the environment where the bot is running
* *Bot ID* 
+
GUID of the bot that is executing the workflow 

_RandomVariable_ is an integer value. All other variables are strings.

Debugging the _Runtime Variables_ action step is not possible. Therefore, the debug functionality is disabled and you cannot set breakpoints for this action step.

== Properties

* *Write Runtime Variables to Logfile* 
+
When enabled, the workflow writes runtime variables to the Stc log file.

== Outbound Variables

* *Runtime Variables.[name of the runtime variables]* 
+
Content of _Runtime variables_.

== Wizard

Use the wizard to add new runtime variables and specify their *Name* and *Description*. 

To make variables available in later transactions, select *Make Variables available in all further Transactions*. 

Use the *Delete* button to remove variables.

The values listed in *Sample Data* are for local testing. If a bot completes the workflow, the workflow re-determines the values at each run.

Some variables such as *Random Variable* show a *Settings* menu that you can expand for further configuring the variable.
