= RPA Builder 6.7.4 Release Notes

RPA Builder is the on-premises application that enables you to build automations by specifying the action steps of the process.

include::partial$release-notes/rn-last-version-message.adoc[] 

== January 13, 2025
 
// == What's New
include::partial$release-notes/rn-headings.adoc[tag=whatsNew,leveloffset=+1]

* Submit Document to MuleSoft IDP and Retrieve Results from MuleSoft IDP action steps now include these inbound variables: 
** *Action ID*
** *Action Version*
** *Anypoint URL*
** *Organisation ID* 
+
See xref:rpa-builder::toolbox-mulesoft-idp-submit-document-to-mulesoft-idp.adoc#inbound-variables[Submit Document to MuleSoft IDP].

* You can now define a custom attribute to read from when using the Get Web Element Text action step. 
* RPA Builder now shows a detailed error message if an installed service or component is missing.  
* The `stc_trace.log` file now includes the OS process ID in the workflow header section.

// == Compatibility
include::partial$release-notes/rn-headings.adoc[tag=compatibility,leveloffset=+1]

[%header%autowidth.spread]
|===
|Application |Version
|RPA Recorder | 6.6.0 and later
|RPA Bot | 1.0.0 and later
|===

include::partial$release-notes/rn-headings.adoc[tag=fixedIssues,leveloffset=+1]

[%header,cols="5a,1a"]
|===
| Issue Resolution | ID
| Read Mail no longer saves attachments outside of the specified folder. | W-16942473
| Saving mail attachments with invalid file names no longer causes an error. RPA Builder replaces the invalid characters and saves the file with the new name. | W-17201344
| Read From Excel File no longer parses cell values incorrectly if the value starts with the `n` character.  | W-17246126
| Log files no longer show an incorrect display name when the Iterate Over Files action step executes.  | W-17259672
| The RPA Builder setup no longer fails to detect some Java editions during the installation process. | W-17339515
| The AI OCR (screen-based) action step no longer shows an error message the first time you click *OK* in the wizard. | W-17395176
|===

[[migrating-oauth-credentials]]
== Migrating OAuth Credentials

As part of the enhancement to Mail Session (OAuth) and the OAuth Credentials activity parameter, RPA Builder 6.7.0 and later versions automatically detect and update any existing OAuth Credentials and remove all existing mappings of this activity parameter. RPA Builder appends `_updated` to migrated activity parameters. 

If your automation projects used OAuth Credentials, follow these steps after upgrading from a version earlier than RPA Builder 6.7.0 to complete the migration process: 

. In RPA Builder, locate the updated OAuth Credentials activity parameters.
. Add the updated activity parameters to the corresponding workflows and map them to the corresponding Mail Session (OAuth) action steps.
. In RPA Manager, create a new OAuth Credential global variable in the credential pool. 
. Map the new global variable with the updated OAuth Credentials activity parameters in the corresponding run configurations.

// == See Also
include::partial$release-notes/rn-headings.adoc[tag=seeAlso,leveloffset=+1]

* https://help.mulesoft.com/s/[MuleSoft Help Center^]
* https://www.mulesoft.com/support-and-services[MuleSoft Services^]
