= RPA Builder 6.7.0 Release Notes

RPA Builder is the on-premises application that enables you to build automations by specifying the action steps of the process.

include::partial$release-notes/rn-last-version-message.adoc[] 

== August 27, 2024 (TBC) //TODO confirm date
 
// == What's New
include::partial$release-notes/rn-headings.adoc[tag=whatsNew,leveloffset=+1]

//new action steps 
* Execute macros on an Excel file with the new Execute Excel Macro action step.
* Download or export files from your Google Workspace  with the new Download from Google Drive action step.
* Upload files to your Google Workspace with the new Upload to Google Drive action step.
* Search files or folders in your Google Workspace and retrieve their name and ID with the new Search for Files and Folders in Google Drive action step.
//enhancements to action steps
* GMAIL NOW SUPPORTS OAUTH //TODO confirm if this is a new AS or updates the existing one
* You can now configure the new Google API Service Account Credentials activity parameter to use for authentication with the Google Drive action steps.
//RPA builder updates 
// * 
//other updates
// * 

// == Compatibility
include::partial$release-notes/rn-headings.adoc[tag=compatibility,leveloffset=+1]

[%header%autowidth.spread]
|===
|Application |Version
|RPA Recorder | 6.6.0 and later
|RPA Bot | 1.0.0 and later
|===

// == Fixed Issues

include::partial$release-notes/rn-headings.adoc[tag=fixedIssues,leveloffset=+1]

[%header,cols="5a,1a"]
|===
| Issue Resolution | ID
| --description-- | W-
|===


// == See Also
include::partial$release-notes/rn-headings.adoc[tag=seeAlso,leveloffset=+1]

* https://help.mulesoft.com/s/[MuleSoft Help Center^]
* https://www.mulesoft.com/support-and-services[MuleSoft Services^]
