= Licensing

When the Process Recorder will be used in Standalone mode (not started via X1 Server web client), a license is required to be able to use the recorder.
When the recorder is started in Standalone for the first time, the following dialog appears [Fig. 15]. To continue using the Process Recorder select “Yes” and insert a license key provided by Servicetrace. Click “No” to close the Process Recorder without inserting a license.

The license can be either a time limited Trial or a Permanent one. After inserting a license key, it will be validated, and the type (trial or permanent) is shown in a confirmation pop up together with the information of the license.
After inserting a valid license, information related to that license can also be found in the About screen [Fig. 16].

If you want to change the license you can import another license key in the [settings pane](xref) of the Process Recorder [Fig 17].

When a time limited trial license expires the dialog from Fig. 15 reappears on start in Standalone to import another valid license.

= Updates

The X1 Process Recorder has an automatic update function, which checks by default at startup if a newer version is available. The user will be notified when a newer version is available and can download and install it directly [Fig. 18]
The automatic check at the start of the X1 Process Recorder can be disabled in the notification and in the settings by disabling the option “Automatically check for updates on startup“.
