= User Interface

== Home

The Home section contains the main controls of the recorder. If the recorder was started from the server, the existing BPMN of the process is also shown here.

//Feedback about the X1 Process Recorder can be sent to Servicetrace via the hyperlink in the bottom right corner “Send Feedback”.

== Recording

New recording session is started via this button, or alternatively by the hotkey F8.
When the recording has been started the main view gets collapsed into a minified view.

On the right there is a timer which indicates total recording time, but also is a visual indicator if recording is running or paused. To pause the recording click on the red circled pause icon or use the hotkey F8. To continue press the recording icon or F8 again.

Recording session is finished via this button. There is no hotkey to directly stop a recording. Right after the recording has been stopped, the application triggers the [Documents](xref:) and BPMN generations.

Manual screenshots can be taken via this button, or alternatively by the hotkey F9. This opens the [Define screenshot](xref:) dialog, in which the user has the option between full-screen or partial area screenshot.

Variables can be entered via this button, or alternatively by the hotkey F10. This opens the [Add variable](xref:) dialog.

Comments can be entered via this button, or alternatively by the hotkey F11. This opens the [Add Comment](xref:) dialog, where user can enter a comment.

New activities can be added directly to the recorded BPMN via this button, or alternatively by the hotkey F12. This opens the [Add Activity](xref:) dialog, where user can add a new activity.
Activities can be X1 Bot Tasks, which represents Workflows done by X1 Bots, User Tasks or External Tasks.
Also automatic creation of new X1 Bot tasks on application change can be enabled / disabled in the [Add Activity](xref:) dialog or in [settings](xref:) of X1 Process Recorder.

During recording, each mouse click is automatically recorded with coordinates and type (left click, right click, etc.). If you want to record a mouse over hover action, hold the mouse pointer over the corresponding position and press the hotkey F2.
This records the coordinates and a mouse over hover action for this position.

== Toast Notifications while recording
With each recording state change, a toast notification is shown indicating current state. The notification stays for 2 seconds and disappears automatically.

== Define Screenshot
The Define screenshot pop-up window, opened with F9 while recording, provides the user with two options for taking screenshots manually [Fig. 4.1].

Before a screenshot is taken the screen will be automatically freeze. The freezing can be delayed by selecting a delay (in seconds) from the dropdown [Fig. 4.2].

The timer delay mechanism will take effect regardless of the chosen screenshot method.

== Add Variable

The add variable pop-up window, opened with F10 while recording, allows the user to add variable information as part of the recording documentation, which will be useful during implementation of the process automation in X1 Design Studio [Fig. 5.1].

The possible variable types are:
* Alphanumeric
* Integer
* Float
* Boolean
* Credential

By clicking *Add* the variable information will be saved to the recording documentation.

[NOTE]
The recording must be paused to add a variable. If the pop-up was opened via the respective hotkey, while recording was running, it will be automatically paused.

== Add Activity

The add activity pop-up window, opened with F12 while recording or by clicking on the button in the minified view, allows the user to manually add an activity as part of the BPMN recording. Enter a name for the Activity and select its type.
The user also has the possibility to enable or disable the function of automatic creation of Activities on application changes.

Possible activity types are:
* X1 Bot Task
* User Task
* External Task

For User Task or External Task no documentation will be recorded. The user is required to enter a description instead. To continue recording add a X1 Bot Task.

[NOTE]
The recording must be paused to add an activity, or change creation mode of the activities. If the pop-up was opened via the respective hotkey, while recording was running, it will be automatically paused.

== Settings

In the settings section the user can configure the recorder application and set preferences. The settings section is divided into three parts:

* Settings
* Language
* Hotkeys

=== Settings Section

The settings are used to configure the X1 Process Recorder application [Fig. 8.1].

* Directory – Local directory folder where the documents (BPMN, PDF and XES) and application logs should be stored.
* Create Process Documentation (PDF) – Option to select whether a process documentation file should be generated as PDF, when recording session has been stopped.
* Create Process Mining files (XES) - Option to select whether a XES process file should be generated, when recording session has been stopped.
* Automatic generation of activities – Option to select whether a X1 Bot Task activity should be genereated automatically when a change in applications is done. E.g. change from Outlook to Excel while recording will create a new Activity for Excel wherein click path documentation will be stored.
* Take screenshot with every mouse click – Optional to choose whether to automatically take a screenshot on every mouse click or not.
** Area around the mouse click – Screenshot taken will be a cropped area around the mouse click, based on the Area size in % (expressed in screen resolution percentage).
    +
    Crop percentage can be within 20-50% screen resolution.
** Full screen – Screenshot taken will include all screens that are connected to user’s machine.
** Mouse click screenshot quality – Quality of the screenshots on every mouse click.
*** Compressed JPEG format
*** Loss-free PNG format
* Merge keystrokes – Keyboard entries entered during the recording can be concatenated into meaningful words & sentences based upon the timestamps when they were entered.
+
Number is expressed in seconds and can range from 2 to 10 seconds.
* Verbosity level – Option to show detailed Process Information in Documentation. If 'Low' the information will not be shown in Documentation.
* Licence type – Shows information about the type of License that is being used. Option to enter another license key by clicking on icon next to license information.
* Automatically check for updates on startup – Automatically checks for newer versions of X1 Process Recorder when application is started. By clicking the icon a manual check for a new version can be done.

=== Language Section

In the language section the user can set the language of the X1 Process Recorder.

If the recorder is started from the X1 Server web client, the language is taken from the user profile.

If the recorder is started as standalone, the first time the language is English, but after a language change, next time it is started as standalone it will have the last saved language.

=== Hotkeys Section

The hotkeys section currently just displays information about the specific hotkeys that can be used, and their purpose.
Hotkeys cannot be changed as of now.

== About Screen

The about screen contains general information about the X1 Process Recorder such as:

* The Version number
* Copyright information
* Licensing information
* Link to Servicetrace website
* Link to Support / Contact information
